export const Provider = {
  id: 0,
  name: "",
  phone: 0,
  ratingOverall: 0.0,
  ratingConnection: 0.0,
  ratingStability: 0.0,
  ratingSpeed: 0.0,
  ratingService: 0.0,
  description: null,
  order: 0,
  image: null,
  plansCount: 0,
  promotionsCount: 0,
  reviewsCount: 0,
  minPrice: 0,
  minInternetSpeedValue: 0.0,
  minInternetSpeedUnits: "",
  maxInternetSpeedValue: 0.0,
  maxInternetSpeedUnits: "",
};
